### ISSUE TITLE
Introduce "human readable" default conversion

### ISSUE THREAD

**Issue by githubNM** [sbglasius/I18nEnumsGrailsPlugin#4]
For example, it would convert:
"IN_PROGRESS" to "In Progress"
"FUTURE_VALUE" to "Future Value"
and so forth

Basically capitalize every word, and convert every underscore into a space. 

Passing a list of words that don't get capitalized unless at the start (so that "of", "in" and "and" can remain as is in the middle of the phrase) as another annotation parameter (or even having a default list taken from some style guide) is a nice to have (so that "KING_OF_ENGLAND" gets converted to "King of England" and not "King Of England"; nevertheless OF_COURSE remains as "Of Course").

**Comment by sbglasius** [comment]
The first part of this is now implemented, the second will be put as a new issue/improvement suggestion
